# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Militante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=18)),
                ('dni', models.CharField(max_length=20)),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesoElectoral.Agrupacion')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agrupacion',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesoElectoral.Partido'),
        ),
    ]
